Cja 34 add routing
frankielb/frankie-barrios-ux-aop pull request #25
Opened 2019-10-22 19:39 UTC by frankiebarrios

## What It Does
This pull request is set to complete Add Routing.

This work is taking place to complete Add Routing.

**Implementation:**
- Routing setup using the Banno Router.
- Separates the app's functionalities into views.
- Adds routing between views.
- Uses routes as a source of data to populate your different views.

## How To Test
- Install dependencies using instruction in README.
- Start server using yarn start or build using yarn build.

## Notes/Caveats

None
## Checklist

Under penalty of public shaming, I avow that I:
**Many items in list N/A** 
- [X] Reviewed the diff to look for typos, whitespace errors, and console.log() statements
- [X] Verified that there are no compiler or linter errors or warnings
- [X] Verified the build in production(optimized) mode
- [X] Updated the docs, if necessary
- [X] Included the appropriate labels
- [X] Referenced applicable issues (i.e. Closes #XXXX, Fixes #XXXX)

Browsers tested:
**Many items in list N/A** 
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge
- [ ] Internet Explorer

## Dependencies
1. Install Node and npm
2. Install Yarn
3. Install Ux-Lint

2019-11-01 15:17 UTC, kddrake reviewed
what's all this `.idea/*` stuff?

2019-11-01 15:22 UTC, frankiebarrios commented
> what's all this `.idea/*` stuff?

@kddrake it's an IntelliJ’s settings folder. Tried a new IDE from JetBrains and had to install some plugins/ extensions and it added that to my project. Deleting it though, not needed.

2019-11-01 15:28 UTC, kddrake requested changes
Things, code wise, are generally looking good. I will say that your `routeEnter` functions a bit more involved than most of our `routeEnter` functions in the platform. That said, if it works, it works. I'm not knowledgeable enough on the router to say whether or not there's a better way.

2019-11-01 15:28 UTC, kddrake commented on src/components/create-user.html
> +    // Routing Imports
your imports are named well... I don't think you need the comment.

2019-11-01 15:28 UTC, kddrake commented on src/components/create-user.html
> +            observer: 'check'
probably nice when deving, but I don't think you'll actually want to merge this.

also, you could do this all in one line:
```suggestion
            observer: (newVal, oldVal) => console.log(newVal)
```

2019-11-01 15:28 UTC, kddrake commented on src/components/create-user.html
> +          currentElement.parentNode.removeChild((currentElement));
why the double wrap of `currentElement`?

2019-11-01 15:28 UTC, kddrake commented on src/components/intern-app.html
> +    // Routing Imports
see other comment about this same comment

2019-11-01 15:28 UTC, kddrake commented on src/components/user-list.html
> +    // Routing Imports
see other comment about this comment

2019-11-01 15:28 UTC, kddrake commented on src/components/user-list.html
> +            observer: 'check'
see other comment about this observer

2019-11-01 15:28 UTC, kddrake commented on src/components/user-profile.html
> +            observer: 'check'
see other comment about this observer

2019-11-01 15:28 UTC, kddrake commented on src/components/user-profile.html
>          this.profileExpanded ? this.profileExpanded = false :
I think this is what you're going for, and much simpler:
```suggestion
        this.profileExpanded = !this.profileExpanded;
```

2019-11-01 15:28 UTC, kddrake commented on src/components/user-profile.html
>          this.buttonText === 'Expand' ? this.buttonText = 'Collapse' :
Would do the same here, as well:
```suggestion
        this.buttonText = !this.buttonText;
```

2019-11-01 15:28 UTC, kddrake commented on src/routing/routes.js
> +  console.log('Tree: ', node);
does this _need_ to be merged?

2019-11-01 16:36 UTC, frankiebarrios commented on src/components/create-user.html
> +          currentElement.parentNode.removeChild((currentElement));
Had something else in there at one time I believe? Removed and all is well still.

2019-11-08 16:17 UTC, kddrake approved these changes
I would have had some other changes I would have liked to have been made, but seeing as I want a focus on LitElement and you've proven you can get the router in your app and get it to work properly, I'ma approve and merge 👍

2019-11-08 16:18 UTC, merged